### DISCUSSION TITLE
Make use of additional Charge Periods...

### DISCUSSION THREAD

**Discussion by smoketabs** [nathanmarlor/foxess_em#345] [Ideas]
I wonder, would it be possible for this integration to make use of the other available charge period when the sun ain't shining?

Or, include a value field in the setup that asks for when your peak period starts/ends (i.e. Flux/Eco7/etc.)

I ask as at the moment I've manually set my second charge period to be on between 1400 and 1555 to get me through the longer evenings whilst avoiding the high FLUX import rates from 1600.

Not a big deal, but if the integration can sort this itself, that would mean I can continue to be super lazy.

Cheers

**Comment by jamesog** [comment]
If you want to do this statically (the same 1400-1555 time period every day) you can set up a Helper that matches that time period, and then an automation that triggers the Force Charge Now service when the helper turns on.

I do something similar to this to manually set force charge periods when Octopus Agile is going to have cheaper rates. I use a Schedule helper, the a Time of Day helper would work too.

Here's the automation:

```yaml
alias: Schedule charge start
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.force_charge
    to: "on"
condition: []
action:
  - service: foxess_em.start_force_charge_now
    data: {}
  - service: notify.slack
    data:
      message: Charge start
      title: Charge start
      target: "#home-assistant"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: Starting a force charge based on schedule
mode: single

```

and a similar one that triggers when the helper turns `off`.
